# Generated by Django 5.2 on 2025-07-07 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_groupmessage_privatemessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='group_images/'),
        ),
    ]
