# Generated by Django 5.2 on 2025-06-11 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_skills'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='skills',
            unique_together={('user', 'name')},
        ),
    ]
