# Generated by Django 5.2 on 2025-06-13 05:10

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_visibility',
            field=models.CharField(choices=[('public', 'Public'), ('organization', 'Organization Only'), ('connection', 'Connections Only')], default='public', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='show_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='show_phone',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='files',
            name='file',
            field=models.FileField(upload_to=accounts.models.file_path),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.user_profile_path),
        ),
    ]
