# Generated by Django 5.2 on 2025-07-05 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('careerhub', '0002_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='reminder',
        ),
    ]
