# Generated by Django 5.2 on 2025-07-08 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('careerhub', '0004_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savedjob',
            old_name='saved_at',
            new_name='created_at',
        ),
    ]
